/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_screenshot_MainActivity */

#ifndef _Included_com_example_screenshot_MainActivity
#define _Included_com_example_screenshot_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_com_example_screenshot_ScreenshotService_startScreenShot (JNIEnv *, jobject, jstring);

JNIEXPORT jboolean JNICALL Java_com_example_screenshot_ScreenshotService_stopScreenShot (JNIEnv *, jobject);

JNIEXPORT jboolean JNICALL Java_com_example_screenshot_MainActivity_isFbAvaliable(JNIEnv *env, jobject obj);

JNIEXPORT jboolean JNICALL Java_com_example_screenshot_MainActivity_playVideo(JNIEnv *env, jobject obj, jstring ip, jstring filename, jint status);

#ifdef __cplusplus
}
#endif
#endif
